### ISSUE TITLE
Mediatype handlers

### ISSUE THREAD

**Issue by makeworld-the-better-one** [makeworld-the-better-one/amfora#121]
Currently there is support for using different applications per URL scheme, see the `[url-handlers]` section of the config. Another section should be made to support defining a list of mediatypes that the specified application would handle. Currently the only option for binary files (images, audio, etc) is to download it or open it in the portal. Adding this would allow more seamless browsing.

The download modal buttons should change to "Open" and "Download". The "Open in Portal" button has always been a bit of a hack.

Example config, using an array of tables

```toml
# Explanation here...

[[mediatype-handlers]]
cmd = ["feh"]
types = ["image/jpeg"]


[[mediatype-handlers]]
cmd = ["vlc", "--flag"]
types = ["audio", "video"] # Can capture an entire type by just not specifying the subtype

[[mediatype-handlers]]
cmd = ["some-command"]
types = [
	"application/pdf",
	"*", # Override the default catch-all handler
]
```

- [x] Put this on the roadmap (also talk about scheme handlers in the same bullet maybe)
- [x] Add way to specify piping/streaming content versus downloading the entire thing first
