### ISSUE TITLE
Bind_tab issue with french keyboard

### ISSUE THREAD

**Issue by bacardi55** [makeworld-the-better-one/amfora#198]
Hi! Thanks for the great work on Amfora!

I downloaded the latest version (1.8.0) today and setup the bind_tab like this:
```toml
bind_tab1 = "&"
bind_tab2 = "é"
bind_tab3 = '"'
bind_tab4 = "'"
bind_tab5 = "("
bind_tab6 = "-"
bind_tab7 = "è"
bind_tab8 = "_"
bind_tab9 = "ç"
bind_tab0 = "à"
```
This is the default values for the number keywords without shift (opposed to US where without shift you have the numbers).

The bind 2 (é), 7 (è), 9 (ç) and 0 (à) do not work, the other do.

I don't have go installed nor go skilled (yet at least :)), but let me know if you need more details.
