### ISSUE TITLE
amfora leaves zombie processes

### ISSUE THREAD

**Issue by dm9pZCAq** [makeworld-the-better-one/amfora#219]
as described in documentation [cmd.Start](https://golang.org/pkg/os/exec/#Cmd.Start) doesn't wait for process completion and it's causes zombie processes

**Comment by makeworld-the-better-one** [comment]
Can you provide more information on why this is an issue? `.Start` is used because some processes may continue forever, and for all the processes Amfora calls, it doesn't care about how or when they finish.

**Comment by dm9pZCAq** [comment]
i have this in `config.toml`:
```toml
http = ['sh', '-c', 'printf %s "${0}" | xclip -selection c']
# ...
[[mediatype-handlers]]
cmd = ['sxiv', '-a', '--']
types = ["image"]
```

and after opening some links and images remain zombies processes
![img](https://0x0.st/-cC9.png)

i'm using [setsid(2)](https://linux.die.net/man/2/setsid) in `C` and in `Go` should be something similar
