### ISSUE TITLE
Center text

### ISSUE THREAD

**Issue by makeworld-the-better-one** [makeworld-the-better-one/amfora#233]
Currently there are two config options controlling how text is formatted overall:

```toml
# A number from 0 to 1, indicating what percentage of the terminal width the left margin should take up.
left_margin = 0.15

# The max number of columns to wrap a page's text to. Preformatted blocks are not wrapped.
max_width = 100
```

I propose `max_width` default to 80 now, and then `left_margin` be removed in favor of an algorithm that gets the current text width and always centers it.
