### ISSUE TITLE
`bkmk_modal_field_bg` and `bkmk_modal_field_text` are switched and other theming oddities

### ISSUE THREAD

**Issue by bzbug** [makeworld-the-better-one/amfora#307]
1. From my current theme:
```toml
bkmk_modal_field_bg = "#cccc66" # yellow
bkmk_modal_field_text = "black"
```

2. Result:

![332x152_ 10 04 2022 18:37](https://user-images.githubusercontent.com/28236673/162624619-389f0bc9-4b25-497d-bc3f-36fead102e60.png)

The colors of text and background are reversed. Yellow is chosen for `bkmk_modal_field_bg` in my theme, yet it works for the text, and `black` is chosen for `bkmk_modal_field_text` in the theme, but it is applied to the background.

---

1. Also, there's something strange going on with the buttons. From my theme:

```toml
btn_bg = "#333333" # dark gray
btn_text = "white"

error_modal_bg = "#773333" # red
error_modal_text = "#110000" # black
```

2. Result:

![331x108_ 10 04 2022 18:43](https://user-images.githubusercontent.com/28236673/162624859-9e310a56-48fd-464e-b25a-7c0e366a6665.png)

Compare the button coloring here and in the previous screenshot. The right one is in the previous, in a download modal. But here the colors are reversed. I didn't find any way to define button colors for different kinds of modals.
