### ISSUE TITLE
Customizable keybindings

### ISSUE THREAD

**Issue by sotpapathe** [makeworld-the-better-one/amfora#88]
Is this a desired feature?

Example section in `config.toml`:

``` toml
[keybindings]
quit = "q"
go_to_bottom = "G"
bookmarks = "Ctrl+b"
```
